package net.latin.server.utils.deleteUseCase.gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import net.latin.server.utils.caseMaker.ui.LookAndFeelUtil;
import net.latin.server.utils.deleteUseCase.domain.DeleteUseCase;
import net.latin.server.utils.projectData.ProjectData;
import net.latin.server.utils.projectData.UseCaseData;
import net.latin.server.utils.projectData.logic.ProjectStructureReader;
import net.latin.server.utils.resources.ResourceFinder;

public class DeleteUseCaseGui extends javax.swing.JFrame implements ListSelectionListener {

	private ProjectData projectData;
	private final String projectPath;
	private DefaultListModel modelo = new DefaultListModel();


    public DeleteUseCaseGui() {

    	projectPath = ResourceFinder.getLocalProjectPath();
		projectData = ProjectStructureReader.getInstance().readProjectStructure(projectPath+"/config/GeneralConfig.xml");


    	configureAppereance();
        initComponents();

        cargarListBox();



        this.setTitle(projectData.getName());
		this.setLocation( 300, 100 );

    }


    private void actionEliminar(final java.awt.event.ActionEvent evt) {
//      ProjectStructureReader.main( new String[]{} );

    	final String texto = "Estás seguro de eleminar el Caso de Uso: "+ labelCaseSelected.getText() + " ?";

    	final int result = JOptionPane.showConfirmDialog(this, texto,projectData.getName(), JOptionPane.YES_NO_OPTION);

    	if (result == 0) {

    		DeleteUseCase.getInstance().borrarCaso( labelCaseSelected.getText(),projectPath, projectData);

    		//DefaultListModel model = (DefaultListModel) this.listBoxCase.getModel();

//    		model.removeElementAt(this.listBoxCase.getSelectedIndex());
    		modelo.remove(this.listBoxCase.getSelectedIndex());
    		//model.removeElementAt(this.listBoxCase.getSelectedIndex());

    	}

    }

    private void actionCancelar(final java.awt.event.ActionEvent evt) {

    }


    private void configureAppereance() {
		try {
    		UIManager.setLookAndFeel( LookAndFeelUtil.getLookAndFeel() );
    	} catch (final Exception ex) {
    		throw new RuntimeException( "Error stting XP look and feel", ex );
    	}
    	SwingUtilities.updateComponentTreeUI( this );
	}

    private void cargarListBox() {
    	listBoxCase.addListSelectionListener(this);

		for (UseCaseData useCase : projectData.getUseCases()) {

    		modelo.addElement(useCase.getNombre());
		}
    	this.listBoxCase.setModel(modelo);
        scrollPanelCase.setViewportView(listBoxCase);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        botonEliminar = new javax.swing.JButton();
        labelCaseSelected = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrollPanelCase = new javax.swing.JScrollPane();
        listBoxCase = new javax.swing.JList();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonEliminar.setText("ELIMINAR");
        botonEliminar.setName("botonEliminar"); // NOI18N
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                actionEliminar(evt);
            }
        });

        labelCaseSelected.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelCaseSelected.setForeground(new java.awt.Color(255, 0, 51));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel2.setText("Seleccione el Caso de Uso a Eliminar");

        jLabel3.setText("Se Borrará:");



        botonCancelar.setText("Cancelar");
        botonCancelar.setName("botonEliminar"); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                actionCancelar(evt);
            }
        });


        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(scrollPanelCase, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(labelCaseSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                        .addGap(189, 189, 189))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollPanelCase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCaseSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEliminar)
                            .addComponent(botonCancelar))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>



    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUseCaseGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCaseSelected;
    private javax.swing.JList listBoxCase;
    private javax.swing.JScrollPane scrollPanelCase;



	public void valueChanged(final ListSelectionEvent e) {

		String elementAt = (String) modelo.getElementAt(listBoxCase.getSelectedIndex());
		labelCaseSelected.setText(elementAt);

	}




}
